/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 1.0.0
 */
export type PostSessionsRefresh200 = {
  refreshToken: string
  token: string
}

export type PostSessionsRefreshBody = {
  refreshToken: string
}

export type GetUsersProfile200 = {
  /** @nullable */
  avatar: string | null
  email: string
  firstName: string
  id: string
  lastName: string
}

export type GetGroupsGroupId200DataBalanceItem = {
  amount: number
  firstName: string
  lastName: string
  memberId: string
}

export type GetGroupsGroupId200Data = {
  balance: GetGroupsGroupId200DataBalanceItem[]
  currency: string
  id: string
  name: string
}

export type GetGroupsGroupId200 = {
  data: GetGroupsGroupId200Data
}

export type GetGroups200DataItem = {
  balance: number
  currency: string
  id: string
  name: string
}

export type GetGroups200 = {
  data: GetGroups200DataItem[]
}
