/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppTransactionIndexImport } from './routes/app/transaction/index'
import { Route as AppFriendsIndexImport } from './routes/app/friends/index'
import { Route as AppActivitiesIndexImport } from './routes/app/activities/index'
import { Route as AppAccountIndexImport } from './routes/app/account/index'
import { Route as AppGroupIdIndexImport } from './routes/app/$group-id/index'
import { Route as AppGroupIdTransactionIdIndexImport } from './routes/app/$group-id/$transaction-id/index'
import { Route as AppGroupIdTransactionIdEditImport } from './routes/app/$group-id/$transaction-id/edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const AppTransactionIndexRoute = AppTransactionIndexImport.update({
  id: '/app/transaction/',
  path: '/app/transaction/',
  getParentRoute: () => rootRoute,
} as any)

const AppFriendsIndexRoute = AppFriendsIndexImport.update({
  id: '/app/friends/',
  path: '/app/friends/',
  getParentRoute: () => rootRoute,
} as any)

const AppActivitiesIndexRoute = AppActivitiesIndexImport.update({
  id: '/app/activities/',
  path: '/app/activities/',
  getParentRoute: () => rootRoute,
} as any)

const AppAccountIndexRoute = AppAccountIndexImport.update({
  id: '/app/account/',
  path: '/app/account/',
  getParentRoute: () => rootRoute,
} as any)

const AppGroupIdIndexRoute = AppGroupIdIndexImport.update({
  id: '/app/$group-id/',
  path: '/app/$group-id/',
  getParentRoute: () => rootRoute,
} as any)

const AppGroupIdTransactionIdIndexRoute =
  AppGroupIdTransactionIdIndexImport.update({
    id: '/app/$group-id/$transaction-id/',
    path: '/app/$group-id/$transaction-id/',
    getParentRoute: () => rootRoute,
  } as any)

const AppGroupIdTransactionIdEditRoute =
  AppGroupIdTransactionIdEditImport.update({
    id: '/app/$group-id/$transaction-id/edit',
    path: '/app/$group-id/$transaction-id/edit',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/$group-id/': {
      id: '/app/$group-id/'
      path: '/app/$group-id'
      fullPath: '/app/$group-id'
      preLoaderRoute: typeof AppGroupIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/activities/': {
      id: '/app/activities/'
      path: '/app/activities'
      fullPath: '/app/activities'
      preLoaderRoute: typeof AppActivitiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/friends/': {
      id: '/app/friends/'
      path: '/app/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/transaction/': {
      id: '/app/transaction/'
      path: '/app/transaction'
      fullPath: '/app/transaction'
      preLoaderRoute: typeof AppTransactionIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/$group-id/$transaction-id/edit': {
      id: '/app/$group-id/$transaction-id/edit'
      path: '/app/$group-id/$transaction-id/edit'
      fullPath: '/app/$group-id/$transaction-id/edit'
      preLoaderRoute: typeof AppGroupIdTransactionIdEditImport
      parentRoute: typeof rootRoute
    }
    '/app/$group-id/$transaction-id/': {
      id: '/app/$group-id/$transaction-id/'
      path: '/app/$group-id/$transaction-id'
      fullPath: '/app/$group-id/$transaction-id'
      preLoaderRoute: typeof AppGroupIdTransactionIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/app/$group-id': typeof AppGroupIdIndexRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/activities': typeof AppActivitiesIndexRoute
  '/app/friends': typeof AppFriendsIndexRoute
  '/app/transaction': typeof AppTransactionIndexRoute
  '/app/$group-id/$transaction-id/edit': typeof AppGroupIdTransactionIdEditRoute
  '/app/$group-id/$transaction-id': typeof AppGroupIdTransactionIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/app/$group-id': typeof AppGroupIdIndexRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/activities': typeof AppActivitiesIndexRoute
  '/app/friends': typeof AppFriendsIndexRoute
  '/app/transaction': typeof AppTransactionIndexRoute
  '/app/$group-id/$transaction-id/edit': typeof AppGroupIdTransactionIdEditRoute
  '/app/$group-id/$transaction-id': typeof AppGroupIdTransactionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/app/$group-id/': typeof AppGroupIdIndexRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/activities/': typeof AppActivitiesIndexRoute
  '/app/friends/': typeof AppFriendsIndexRoute
  '/app/transaction/': typeof AppTransactionIndexRoute
  '/app/$group-id/$transaction-id/edit': typeof AppGroupIdTransactionIdEditRoute
  '/app/$group-id/$transaction-id/': typeof AppGroupIdTransactionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/$group-id'
    | '/app/account'
    | '/app/activities'
    | '/app/friends'
    | '/app/transaction'
    | '/app/$group-id/$transaction-id/edit'
    | '/app/$group-id/$transaction-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/$group-id'
    | '/app/account'
    | '/app/activities'
    | '/app/friends'
    | '/app/transaction'
    | '/app/$group-id/$transaction-id/edit'
    | '/app/$group-id/$transaction-id'
  id:
    | '__root__'
    | '/'
    | '/app/'
    | '/login/'
    | '/app/$group-id/'
    | '/app/account/'
    | '/app/activities/'
    | '/app/friends/'
    | '/app/transaction/'
    | '/app/$group-id/$transaction-id/edit'
    | '/app/$group-id/$transaction-id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppIndexRoute: typeof AppIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  AppGroupIdIndexRoute: typeof AppGroupIdIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppActivitiesIndexRoute: typeof AppActivitiesIndexRoute
  AppFriendsIndexRoute: typeof AppFriendsIndexRoute
  AppTransactionIndexRoute: typeof AppTransactionIndexRoute
  AppGroupIdTransactionIdEditRoute: typeof AppGroupIdTransactionIdEditRoute
  AppGroupIdTransactionIdIndexRoute: typeof AppGroupIdTransactionIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppIndexRoute: AppIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  AppGroupIdIndexRoute: AppGroupIdIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppActivitiesIndexRoute: AppActivitiesIndexRoute,
  AppFriendsIndexRoute: AppFriendsIndexRoute,
  AppTransactionIndexRoute: AppTransactionIndexRoute,
  AppGroupIdTransactionIdEditRoute: AppGroupIdTransactionIdEditRoute,
  AppGroupIdTransactionIdIndexRoute: AppGroupIdTransactionIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app/",
        "/login/",
        "/app/$group-id/",
        "/app/account/",
        "/app/activities/",
        "/app/friends/",
        "/app/transaction/",
        "/app/$group-id/$transaction-id/edit",
        "/app/$group-id/$transaction-id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/app/$group-id/": {
      "filePath": "app/$group-id/index.tsx"
    },
    "/app/account/": {
      "filePath": "app/account/index.tsx"
    },
    "/app/activities/": {
      "filePath": "app/activities/index.tsx"
    },
    "/app/friends/": {
      "filePath": "app/friends/index.tsx"
    },
    "/app/transaction/": {
      "filePath": "app/transaction/index.tsx"
    },
    "/app/$group-id/$transaction-id/edit": {
      "filePath": "app/$group-id/$transaction-id/edit.tsx"
    },
    "/app/$group-id/$transaction-id/": {
      "filePath": "app/$group-id/$transaction-id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
