/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppAboutImport } from './routes/app/about'
import { Route as AppGroupIdImport } from './routes/app/$group-id'

// Create/Update Routes

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const AppAboutRoute = AppAboutImport.update({
  id: '/app/about',
  path: '/app/about',
  getParentRoute: () => rootRoute,
} as any)

const AppGroupIdRoute = AppGroupIdImport.update({
  id: '/app/$group-id',
  path: '/app/$group-id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/$group-id': {
      id: '/app/$group-id'
      path: '/app/$group-id'
      fullPath: '/app/$group-id'
      preLoaderRoute: typeof AppGroupIdImport
      parentRoute: typeof rootRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/app/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/app/$group-id': typeof AppGroupIdRoute
  '/app/about': typeof AppAboutRoute
  '/app': typeof AppIndexRoute
}

export interface FileRoutesByTo {
  '/app/$group-id': typeof AppGroupIdRoute
  '/app/about': typeof AppAboutRoute
  '/app': typeof AppIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/app/$group-id': typeof AppGroupIdRoute
  '/app/about': typeof AppAboutRoute
  '/app/': typeof AppIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app/$group-id' | '/app/about' | '/app'
  fileRoutesByTo: FileRoutesByTo
  to: '/app/$group-id' | '/app/about' | '/app'
  id: '__root__' | '/app/$group-id' | '/app/about' | '/app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppGroupIdRoute: typeof AppGroupIdRoute
  AppAboutRoute: typeof AppAboutRoute
  AppIndexRoute: typeof AppIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppGroupIdRoute: AppGroupIdRoute,
  AppAboutRoute: AppAboutRoute,
  AppIndexRoute: AppIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/app/$group-id",
        "/app/about",
        "/app/"
      ]
    },
    "/app/$group-id": {
      "filePath": "app/$group-id.tsx"
    },
    "/app/about": {
      "filePath": "app/about.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
