@baseUrl = http://localhost:3000
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTNiNWVmZS05ZWUxLTRiNjMtOTE3ZS1jZTc0MzEyYmE5M2MiLCJpYXQiOjE5MjA1MTQ1MzV9.KP9XaFC0Aw1rk3IDYkS0G_KoYkZ6uAJU56tHdp5X_jA
@firstGroupId = 41d33f94-d875-4327-b95b-4fa0f1ace8e7
@newGroupId = {{createGroup.response.body.id}}
@firstUserId = 6e3b5efe-9ee1-4b63-917e-ce74312ba93c
@secondUserId = eee51c9a-de9f-42c6-8add-15b7097b30a2
@thirdUserId = 5909f340-69fa-4db5-a728-47777e017cf7
@fourthUserId = 85e36457-77ee-412f-9577-8912da5c80c5
@fifthUserId = 75f9f70b-6cc8-4098-85c8-03b3756e2517
@firstGroupTransactionId = 3774d0b4-a268-4864-b90f-a26a9dd4c321

# @name getGroups
GET {{baseUrl}}/groups
Authorization: Bearer {{jwtToken}}

###

# @name getGroupById
GET {{baseUrl}}/groups/{{firstGroupId}}
Authorization: Bearer {{jwtToken}}

###

# @name createGroup
POST {{baseUrl}}/groups
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Group test",
  "currency": "BRL"
}

###

# @name joinGroup
POST {{baseUrl}}/groups/{{firstGroupId}}/join-group
Authorization: Bearer {{jwtToken}}

###

# @name leaveGroup
POST {{baseUrl}}/groups/{{firstGroupId}}/leave-group
Authorization: Bearer {{jwtToken}}

###

# @name removeGroupMember
POST {{baseUrl}}/groups/{{firstGroupId}}/remove-group-member
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "memberId": "{{secondUserId}}"
}

###

# @name updateGroup
PATCH {{baseUrl}}/groups/{{firstGroupId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Group test updated",
  "currency": "USD"
}

###

# @name deleteGroup
DELETE {{baseUrl}}/groups/{{newGroupId}}
Authorization: Bearer {{jwtToken}}

###

# @name getGroupTransactionsByGroupId
GET {{baseUrl}}/groups/{{firstGroupId}}/transactions
Authorization: Bearer {{jwtToken}}

###

# @name getGroupTransactionById
GET {{baseUrl}}/groups/{{firstGroupId}}/transactions/{{firstGroupTransactionId}}
Authorization: Bearer {{jwtToken}}

###

# @name createGroupTransaction
POST {{baseUrl}}/groups/{{firstGroupId}}/transactions
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Test transaction",
  "amount": 10000,
  "payerMemberId": "{{firstUserId}}",
  "participants": [
    {
      "memberId": "{{firstUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{secondUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{thirdUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{fourthUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{fifthUserId}}",
      "amount": 2000
    }
  ],
  "date": "2024-01-01"
}

###

# @name updateGroupTransaction
PATCH {{baseUrl}}/groups/{{firstGroupId}}/transactions/{{firstGroupTransactionId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Test transaction",
  "amount": 5000,
  "payerMemberId": "{{firstUserId}}",
  "participants": [
    {
      "memberId": "{{firstUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{secondUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{thirdUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{fourthUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{fifthUserId}}",
      "amount": 1000
    }
  ],
  "date": "2024-01-01"
}

###

# @name deleteGroupTransaction
DELETE {{baseUrl}}/groups/{{firstGroupId}}/transactions/{{firstGroupTransactionId}}
Authorization: Bearer {{jwtToken}}
