name: Create PR Domain

# This workflow is a workaround for the lack of support for the `pull_request` event in Railway.
# It creates a domain for the server, client and www apps of the PR environment.

on:
  pull_request:
    branches: [main]

jobs:
  cd:
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Extract PR Number
        id: pr_number
        run: echo "::set-output name=number::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Create domain for server app
        run: |
          railway link -p divisio -s server -e divisio-pr-${{ steps.pr_number.outputs.number }} &&
          railway variables --set "GOOGLE_OAUTH_REDIRECT_URL=https://server-divisio-pr-${{ steps.pr_number.outputs.number }}.up.railway.app/sessions/oauth/google" \
                            --set "NODE_ENV=development" \
                            --set "JWT_SECRET=secret" \
                            --set "PORT=3000" &&
          railway domain

      - name: Create domain for www app
        run: |
          railway link -p divisio -s www -e divisio-pr-${{ steps.pr_number.outputs.number }} &&
          railway variables --set "PORT=3002" &&
          railway domain
